### ISSUE TITLE
Devtools Check warns for orphaned package logistf::

### ISSUE THREAD

**Issue by gabrielodom** [georgheinze/logistf#33]
Hi,
I'm building a package for submission to Bioconductor, and one of my methods depends on Firth Logistic Regression. When I check my package, I get this message:
```
W  checking package dependencies (4.8s)
   Requires orphaned package: ‘logistf’
```

I see that you have closed some GitHub issues recently, so I assume that this warning is by mistake. Please adivse.

**Comment by ljiricka** [comment]
Hi, 
the package was orphaned for a few days, but we submitted a new version to CRAN a week ago.
