### ISSUE TITLE
data input for backward()

### ISSUE THREAD

**Issue by KLuijken** [georgheinze/logistf#34]
Hi,

A question about the updated package. I'm using logistf() and backward() in a simulation project, and with the newest version, backward() provides and error: simpleError in terms.formula(formula, data = data): 'data' argument is of the wrong type.

It seems to me that the data argument is passed on differently compared to the previous version, as there no longer is a 'data' return in logistf().

Notably, the example of the documentation runs without errors:

data(sex2)
fit<-logistf(data=sex2, case~1, pl=FALSE)
fitf<-forward(fit, scope = c("dia", "age"))

fit2<-logistf(data=sex2, case~age+oc+vic+vicl+vis+dia)
fitb<-backward(fit2)

Happy to hear your thoughts!

Kind regards, Kim

**Comment by ljiricka** [comment]
Hi, 
could you provide a simple example where the error occurs? 
Thank you in advance!

**Comment by KLuijken** [comment]
Sure! This would be an example:

`library(logistf)
library(MASS)


# Generate data ----
set.seed(50136465)

# Compute nobs from set number of events and varying eventrate
nobs         <- 250
nL           <- 24

# Generate Y, A and L
sigL         <- matrix(0.3, 
                       nrow = nL,
                       ncol = nL)
diag(sigL)   <- 1
L <- mvrnorm(nobs, mu=rep(0, times = nL), Sigma = sigL)

# Store covariate effects
betasAL <- c(rep(log(1.05), times=(nL/2)),
             rep(0,times=(nL/2)))

betasYL <- c(rep(log(1.05), times=(nL/2)),
             rep(0,times=(nL/2)))

# Generate exposure:
A <- rbinom(nobs, 1, plogis(L %*% betasAL))

# Generate outcome:
Y <- rbinom(nobs, 1, plogis(-1.42 + 
                              L %*% betasYL))

data <- data.frame(Y,A,L)
colnames(data) <- c("Y","A",paste0("L",1:nL))

# Analyse data ----
full              <- logistf(as.formula(paste(c("Y~A" ,paste0("L",1:nL)),collapse = "+")),
                                          data = data,
                                          pl = FALSE,
                                          control = logistf.control(maxit = 50, maxstep = 2),
                                          firth = FALSE,
                                          flic = TRUE)

selected          <- backward(object = full,
                                    slstay = 0.157,
                                    trace = FALSE,
                                    scope = c(paste0("L",(1:nL))))
`

**Comment by ljiricka** [comment]
Thank you! the problem was the update of the logistf object, which could not find the data.frame 'data' but used the function data. Additionally, another bug was fixed. 
You can install the newest version with: 'devtools::install_github("georgheinze/logistf", ref="develop")'

**Comment by KLuijken** [comment]
Many thanks for your help and swift response, Lena! The code runs without any issues now!
