### ISSUE TITLE
Backward cannot handle factors

### ISSUE THREAD

**Issue by KLuijken** [georgheinze/logistf#35]
Hi,

The updated backward function seems to have lost its ability to properly handle variables that were defined as factors in the original data set. A small example:

# load example data logistf package
data(sex2)

# create factor with three levels
sex2$vicl[1:20] <- 2
sex2$vicl <- as.factor(sex2$vicl)

# fit logistf and perform backward elimination
fit<-logistf(data=sex2, case~age+oc+vic+vicl+vis+dia)
fitb<-backward(fit)

> Error in model.matrix.default(test, model.frame(object)) : 
  model frame and formula mismatch in model.matrix()

Kind regards,

**Comment by ljiricka** [comment]
Thank you very much for your help! Bug is fixed.

**Comment by KLuijken** [comment]
Thank you for fixing the bug!

When I implement it, another error comes up

Error in eval(predvars, data, env) : 
  object '[Variable][Level]' not found
Called from: eval(predvars, data, env)

from logistf(); mf[[1L]] <- quote(stats::model.frame).

Can it be that the factorlevels are somehow not handled correctly yet?

**Comment by ljiricka** [comment]
Thank you for providing a dataset that made it much easier to find and fix the bug. 
You can install the newest version with: 'devtools::install_github("georgheinze/logistf", ref="develop")'

**Comment by KLuijken** [comment]
Wow, I'm deeply impressed with the speed at which you get back on all issues! Many thanks!
