### ISSUE TITLE
I cannot find the residuals of the model 

### ISSUE THREAD

**Issue by IlhemB** [georgheinze/logistf#37]
I'm using logistf package in R to handle the problem of the complete separation for logistic regression but I cannot find the residual of the model. Is there any way to extract the residuals?

**Comment by ljiricka** [comment]
Currently it is not possible to directly extract the residuals of the fit. But you can compute the residuals as follows: 

```r
fit<-logistf(case ~ age+oc+vic+vicl+vis+dia, data=sex2, firth=FALSE,pl=FALSE, control = logistf.control(maxit=50))
summary(fit)
y <- sex2$case
#Basic residuals (response residuals): 
y - fit$predict

#Standardized pearson residuals:
(y - fit$predict)/(sqrt(diag(fit$var)))

#Deviance residuals: 
-sign(y - fit$predict)*sqrt(-2*(y*log(fit$predict)+(1-y)*log(1-fit$predict)))
```
