### ISSUE TITLE
drop1 doesn't work with factors

### ISSUE THREAD

**Issue by anon94041** [georgheinze/logistf#38]
Perhaps similar to the issue with the backward function reported in Oct. 2020: drop1() isn't working with factor variables.  Haven't tested add1().

Example: 

data(sex2)
#create factor with three levels
sex2$vicl[1:20] <- 2
sex2$vicl <- as.factor(sex2$vicl)
#fit logistf and apply drop1
fit<-logistf(data=sex2, case~age+oc+vic+vicl+vis+dia)
fitb<- drop1(fit)

Error in model.matrix.default(test, model.frame(object)) :
model frame and formula mismatch in model.matrix()

Thanks in advance.

**Comment by ljiricka** [comment]
Thank you! This has already been solved on the develop branch. We are planning to submit the new version to CRAN in a few weeks.

**Comment by nbarrowman** [comment]
I had exactly this problem with version 1.24 of the package. It worked fine in version 1.23.

Thanks.

**Comment by gregorsteiner** [comment]
Hi, sorry for the late response. This problem was fixed in version 1.24.1.
