### ISSUE TITLE
flac() does not accept formula of the form flac(y ~ . , data)

### ISSUE THREAD

**Issue by VIllager-A** [georgheinze/logistf#46]
![Screenshot from 2022-04-05 12-41-09](https://user-images.githubusercontent.com/46561671/161680253-737643f9-d16f-4249-80af-c441e7dbf348.png)

**Comment by gregorsteiner** [comment]
Hi, thanks for raising this issue. I fixed the problem (see linked pull request) and flac() should now also accept formulas of the form "y ~ .". This will be on CRAN with the next update.
