### ISSUE TITLE
logistf.fit: Maximum number of iterations for full model exceeded. [...] Nonconverged PL confidence limits: maximum number of iterations for variables

### ISSUE THREAD

**Issue by asafbenj** [georgheinze/logistf#47]
I've tried increasing `maxiter` (up to 1e7) and altering `maxstep` (between 1 and 10) as the warning suggests, but it doesn't help. I have 76 observations and 22 variables. Data has been ZCA-whitened. Data is perfectly linearly separable, which is why I'm trying to use `logistf` in the first place.
I get separate warnings for each variable:

```
Warning messages:
1: In logistf(data = profTabZca, formula = GroupType ~ .,  ... :
  logistf.fit: Maximum number of iterations for full model exceeded. Try to increase the number of iterations or alter step size by passing 'logistf.control(maxit=..., maxstep=...)' to parameter control
2: In logistpl(x, y, beta, i, LL.0, firth, 1, offset, weight,  ... :
  fitted probabilities numerically 0 or 1 occurred for variable (Intercept)
...
28: In logistf(data = profTabZca, formula = GroupType ~ .,  ... :
  Nonconverged PL confidence limits: maximum number of iterations for variables: (Intercept), var_name1, ..., var_nameN exceeded. Try to increase the number of iterations by passing 'logistpl.control(maxit=...)' to parameter plcontrol

```
I can share the data if it helps...
Thanks!

**Comment by georgheinze** [comment]
Without having seen the data, I think a logistic regression problem with 76 observations and 22 variables is not solvable, not even with Firth's correction. You would need to apply ridge regression or Lasso. Still, one should also ask what research question that model should answer with so few data?
